apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-injector
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-operator
subjects:
- kind: ServiceAccount
  name: vault-injector
roleRef:
  kind: Role
  name: secrets-operator
  apiGroup: rbac.authorization.k8s.io
