apiVersion: v1
kind: ServiceAccount
metadata:
  name: hvault-auth-delegator
  namespace: vault-injector
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hvault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: hvault-auth-delegator
  namespace: vault-injector