apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "secrets_operator_role_name" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]