apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
{{- include "secrets_operator_role_name" . | indent 2 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]