apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.vault_injector_sa.name }}-secrets-operator
subjects:
- kind: ServiceAccount
  name: {{ .Values.vault_injector_sa.name }}
roleRef:
  kind: Role
{{- include "secrets_operator_role_name" . | indent 2 }}
  apiGroup: rbac.authorization.k8s.io