{{- if eq .Values.schedule_first_job_immediately true }}
apiVersion: v1
kind: Pod
metadata:
  name: vault-secrets-injector-helm-hook
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  serviceAccountName: {{ .Values.vault_injector_sa.name }}
  restartPolicy: Never
  containers:
{{- include "vault_injector_container" . | indent 4 }}
{{- end }}