################
# - vars:
#     vault_token
#     auth_engine_name
################

- hosts: localhost
  gather_facts: false
  vars:
    namespace: kube-system
    vault_token: 
    vault_addr:
  tasks:
    - name: Creating hvault-auth-delegator ServiceAccount
      k8s:
        state: present
        namespace: kube-system
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: hvault-auth-delegator

    - name: Binding hvault-auth-delegator ServiceAccount to the ClusterRole system:auth-delegator
      k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1beta1
          kind: ClusterRoleBinding
          metadata:
            name: hvault-auth-delegator
          subjects:
          - kind: ServiceAccount
            name: hvault-auth-delegator
            namespace: '{{ namespace }}'
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:auth-delegator


    - name: Gettign hvault-auth-delegator ServiceAccount from kube-system namespace
      k8s_info:
        namespace: '{{ namespace }}'
        name: 'hvault-auth-delegator'
        kind: ServiceAccount
      register: vault_sa

    - name: Getting hvault-auth-delegator ServiceAccount Secret
      k8s_info:
        namespace: '{{ namespace }}'
        name: '{{ vault_sa.resources[0].secrets[0].name }}'
        kind: Secret
      register: vault_sa_token_secret

    - name: Getting cluster CA certificate and token
      set_fact:
        ca_cert: "{{ vault_sa_token_secret.resources[0].data['ca.crt'] | b64decode }}"
        k8s_token: "{{ vault_sa_token_secret.resources[0].data['token'] | b64decode }}"

    - name: Making request to the Vault

# {
#             "apiVersion": "v1",
#             "kind": "ServiceAccount",
#             "metadata": {
#                 "creationTimestamp": "2021-01-12T17:38:53Z",
#                 "name": "hvault-auth-delegator",
#                 "namespace": "kube-system",
#                 "resourceVersion": "6078",
#                 "uid": "ad769928-4c97-4607-a61c-733a36408ff9"
#             },
#             "secrets": [
#                 {
#                     "name": "hvault-auth-delegator-token-44q76"
#                 }
#             ]
#         }